config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :charges
  resources :teams, only: [:index]
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :admin, foreign_key: "admin_id", class_name: "User"
	has_many :attendances
	has_many :attendees, class_name: "User", through: :attendances, foreign_key: "attendee_id"

	validates :start_date,
		presence: { message: "Tu as oublié la date de l'évènement !" }
		validate :start_date_cannot_be_in_the_past

	validates :duration,
		presence: { message: "Tu as oublié la durée de l'évènement !" },
		numericality: { only_integer: true, greater_than: 0 }
		validate :duration_multiple_of_5

	validates :title,
		presence: { message: "Tu as oublié le titre de l'évènement !" },
		length: { minimum: 5, maximum: 140, too_short: "Ton titre est trop court, au moins 5 caractères !", too_long: "Ton titre est trop long, maximum 140 caractères !" }

	validates :description,
		presence: { message: "Tu as oublié la description de l'évènement !" },
		length: { minimum: 20, maximum: 1000, too_short: "Ta description est trop courte, au moins 20 caractères !", too_long: "Ta description est trop longue, maximum 1000 caractères !" }

	validates :price,
		presence: { message: "Tu as oublié le prix de l'évènement !" },
		numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000, message: "Non il faut ton prix soit compris entre 1 & 1000" }

	validates :location,
		presence: { message: "Tu as oublié le lieu de l'évènement !" }

	def start_date_cannot_be_in_the_past
		if start_date != nil
			if start_date < Time.now
				errors.add(:start_date, "T'es pas Marty McFly, tu peux pas allez dans le passé bro !")
			end
		end
	end

	def duration_multiple_of_5
		if duration != nil
			if duration % 5 != 0 && duration > 0
				errors.add(:duration, "Un multiple de 5 et on balance ton event dans les bacs !")
			end
		end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
  end

  def show
    @end_date = end_date
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end

    def end_date
      @event.start_date + @event.duration * 60
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :duration, placeholder: "Durée" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :title, placeholder: "Titre" %>
  </div>

  <div class="field mb-3">
    <%= form.text_area :description, placeholder: "Description"%>
  </div>

  <div class="field mb-3">
    <%= form.number_field :price, placeholder: "Prix" %>
  </div>

  <div class="field">
    <%= form.text_field :location, placeholder: "Lieu" %>
  </div>

  <div class="actions d-flex justify-content-center mt-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="d-flex justify-content-center text-primary">Nos évènements </h1>
<hr/>



<br>




<% @events.each do |event| %>

<div class="container">
  <div class="card-media">
    <!-- media container -->
    <div class="card-media-object-container">
      <div class="card-media-object" style="background-image: url(https://picsum.photos/800/600?image=<%= 190 + event.id %>);"></div>
      <ul class="card-media-object-social-list">
        <li>
          <img src="http://lorempixel.com/50/50/people/<%= event.id %>" class="">
        </li>
      </ul>
    </div>
    <!-- body container -->
    <div class="card-media-body">
      <div class="card-media-body-top">
        <span class="subtle"> <%= event.start_date.strftime("%d/%m/%Y") %> à <%= event.start_date.strftime("%Hh%M") %></span>
        <div class="card-media-body-top-icons u-float-right">
          <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"/>
          </svg>
          <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
            <path d="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"/>
            <path d="M0 0h24v24H0z" fill="none"/>
          </svg>
        </div>
      </div>
      <span class="card-media-body-heading"><%= event.title %></span>
      <div class="card-media-body-supporting-bottom">
        <span class="card-media-body-supporting-bottom-text subtle"><%= event.location %></span>
        <span class="card-media-body-supporting-bottom-text subtle u-float-right"><%= event.price %>€</span>
      </div>
      <div class="card-media-body-supporting-bottom card-media-body-supporting-bottom-reveal">
        <a class="card-media-body-supporting-bottom-text card-media-link u-float-right"> <%= link_to 'Voir', event %></a>
        <a class="card-media-body-supporting-bottom-text card-media-link u-float-right text-primary"> by <%= event.admin.first_name %></a>
      </div>
    </div>
  </div>

</div>
<% end %>

app/views/events/new.html.erb
<div class="d-flex justify-content-center text-primary mt-5 mb-3">
<h1>Créer un évènement</h1>
</div>
<div class="d-flex justify-content-center">
<%= render 'form', event: @event %>
</div>
<div class="d-flex justify-content-center mt-3">
<%= link_to 'Retour', events_path %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h2 class="text-center text-secondary font-italic mt-5"><strong><%= @event.title %></strong></h2>
  <hr/>
  
  <div class="d-flex justify-content-center w-25">
    <img class="" src="https://picsum.photos/800/600?image=<%= 190 + @event.id %>">
  </div>

  <div>
  <p><strong class="text-primary mt-4">Description:</strong><br><%= @event.description %></p>
  <p><strong class="text-primary mt-4">Lieu: </strong><%= @event.location %></p>
  <p><strong class="text-primary">Prix:</strong><%= @event.price %>€</p>
  </div>



  <p class="d-flex justify-content-end align-items-center mr-2 text-secondary">
    <span class="text-primary text-capitalize mr-1">Organisé</span><span class="text-primary mr-1">par</span>
    <span class=""><%= @event.admin.email %></span>
    <img src="http://lorempixel.com/50/50/people/<%= @event.id %>" class="ml-2">
  </p>

  <table id="test" class="table table-striped table-hover ">
    <thead>
      <tr>
        <th scope="col" class="text-center">Début</th>
        <th scope="col" class="text-center">Durée</th>
        <th scope="col" class="text-center">Fin</th>
      </tr>
    </thead>
    <tbody >
      <tr>
        <td class="text-center"><%= @event.start_date.strftime("%d/%m/%Y") %> à <%= @event.start_date.strftime("%Hh%M") %></td>
        <td class="text-center"><%= @event.duration %> minutes </td>
        <td class="text-center"><%= @end_date.strftime("%d/%m/%Y") %> à <%= @end_date.strftime("%Hh%M") %></td>
      </tr>
    </tbody>
  </table>

  <hr/>

  <% if is_admin? == true  %>

  <p>
    <strong>Participants:</strong>
    Il y a <%= @event.attendees.count %> participants à votre évènement :<br>
    <% @event.attendees.each do |attendee| %>
      <%= attendee.first_name + ' ' + attendee.last_name %><br>
    <% end %>
  </p>
  <div class="d-flex justify-content-center mb-4">
    <a  class="btn btn-primary mr-2" href="<%= edit_event_path(@event) %>" >Editer</a>
    <a  class="btn btn-danger mr-2" href="<%= @event %>" data-method="DELETE" data-confirm="Tourne 7 fois ta langue dans ta bouche... Tu es certain ?">Supprimer l'évènement</a>
    <a  class="btn btn-primary" href="<%= events_path %>" >Retour</a>
  </div>
  <% else %>
    <% if Event.find(params[:id]).attendees.include? current_user %>
      <div class="d-flex justify-content-center mb-4">
        <button type="button" class="btn btn-success" disabled><i class="fas fa-check mr-2"></i>Tu as déjà rejoint cet évènement</button>
        <a  class=" btn btn-primary ml-3" href="<%= events_path %>" >Retour</a>
      </div>
    <% else %>
      <div class="d-flex justify-content-center mb-4">
        <a class="btn btn-primary mr-2" href="<%= new_charge_path(params[:id]) %>">Rejoindre l'event</a>
        <a  class=" btn btn-primary" href="<%= events_path %>" >Retour</a>
      </div>
    <% end %>
  <% end %>
</div>