config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :charges
  resources :teams, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title >LeChoixDansLaDate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/united/bootstrap.min.css"  crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"  crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"  crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand text-white" href="<%= root_path %>">Le Choix dans la Date <i class=" ml-2 fas fa-hand-point-up"></i></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white"  href="<%= new_event_path %>">Créer un évènement </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="<%= users_path %>">Utilisateurs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="<%= teams_path %>">Equipe</a>
      </li>
    </ul>
  </div>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon profil</a>
          <a class="dropdown-item" data-method="delete" href="<%= destroy_user_session_path %>">Se déconnecter</a>
        </div>
      </li>
      <% else %>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire / Se connecter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
          <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</nav>





    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>